In [3]:
import torch

In [12]:
scalar = torch.tensor(4)
print(scalar, scalar.dtype, scalar.shape, scalar.ndim)

tensor(4) torch.int64 torch.Size([]) 0


In [13]:
vector = torch.tensor([1.0, 2, 3, 4])
print(vector, vector.dtype, vector.shape, vector.ndim)

tensor([1., 2., 3., 4.]) torch.float32 torch.Size([4]) 1


In [14]:
matrix = torch.tensor([[5, 6], [7, 8]])
print(matrix, matrix.dtype, matrix.shape, matrix.ndim)

tensor([[5, 6],
        [7, 8]]) torch.int64 torch.Size([2, 2]) 2


In [15]:
tensor = torch.tensor([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])
print(tensor, tensor.dtype, tensor.shape, tensor.ndim)

tensor([[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]) torch.int64 torch.Size([2, 2, 2]) 3
